# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: da0781e3a85419ce3dcb1ceee133f65113d02cd40a0d673a02936f3c303af517664e19058098d4f8cb85a1843240a6e4e1aed5b667cbb145eef932d433b8f362

test:
  secret_key_base: f93d18874f2d0553e7d5c9fd87e2a15cc4359f41b8aa0e82d280b115e59124621de29dd3a4b9550eeaf08eb8bda2418ec1bf88e7c655c621856e96a5db36ccf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 2d31d8c2de7001fad1cccbb40f7e8f3b1a2aa346ba991a34b2fed5ff141e6cb7093ab0b37ec61316e7d913df970f6564dafcdd9f20242f7d2381ff4a139aee6f
